# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Isabel Omness
title: Aspiring Student
email: omnessis@msu.edu
# email_title: Email (Email title override)
phone: 111-111-1111
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: faketwittername
github_username:  omnessis
stackoverflow_username: "fakename.isabel"
facebook_username: isabel.omness
# flickr_username: jekyll
instagram_username: fake.instaname.isabel
linkedin_username: Isabel Omness
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
 # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  #url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I'm from Shelby, Michigan and currently pursuing my degree with the goal of becoming an actuary. 
    I love spending time outdoors, playing soccer, and being with my family. 
    Music is a big part of my life—I enjoy exploring all kinds of genres. 
    I'm passionate about learning and excited for where this journey takes me!
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Student Summit Event Coordinator
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: 2022
        additional_links:
          - #title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - #title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Event for all students at the Academy of Science, Math, Technoloogy Early College High School
        description: | # this will include new lines to allow paragraphs
          Organized a student summit including field games, breakout sessions, and catering. Oversaw transitions, set up, and team coordination across all parts of the event.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: West Shore Bank
        sub_title: Persoonal Banking Representative 1
        caption: June 2023 - Present
        #link: Link to company (optional)
        quote: >
          West Shore Bank is a local, community based bank
        description: | # this will include new lines to allow paragraphs
          - Helped customers open, manage, and close all types of accounts  
          - Maintained a balanced cash drawer and handled daily transactions  
          - Participated in business meetings and worked across departments  
          - Provided strong customer service and financial guidance 
    #content: 
      - layout: left
        title: West Community College
        sub_title: Payroll Assistant (Student Worker)
        caption: October 2022 - May 2024
        #link: Link to company (optional)
        #quote: >
          #West Shore Bank is a local, community based bank
        description: | # this will include new lines to allow paragraphs
           - Updated and maintained employee payroll and HR records  
           - Handled front desk responsibilities and answered inquiries  
           - Used Excel, Word, Docubase, and Jenzabar to manage records  

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Michigan State University
        sub_title: Bachelor’s Degree in Data Science (In Progress)
        caption: Expected May 2026
        #quote: >
         # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
              Pursuing a degree in Data Science, with the goal of becoming an actuary.
    content:
      - layout: top-left
        title: West Shore Community College
        sub_title: Associate’s Degree in Science 
        caption: September 2022 - May 2024
            #quote: >
            # Short institution or course description (optional)
            #description: | # this will include new lines to allow paragraphs
             #     Pursuing a degree in [Your Major or Area of Study], with the goal of becoming an actuary.
  - title: Skills
    layout: list
    content:  # this will include new lines to allow paragraphs
    - layout: left
      title: Technical Skills
      description: >
        Python, R, Git, VS Code, Microsoft Excel, Microsoft Word, Docubase, Jenzabar

    - layout: left
      title: Analytical & Professional Skills
      description: >
        Data Analysis, Problem Solving, Statistical Reasoning, Customer Service, Cash Handling, Time Management, Communication

    - layout: left
      title: Soft Skills
      description: >
        Teamwork, Leadership, Adaptability, Attention to Detail, Fast Learner, Public Speaking

# Footer
footer_show_references: true
references_title: References on request 

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
